name: '😺 Automatic pull request review'

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  workflow:
    uses: dshare-inc/.github/.github/workflows/auto-approve.yml@main
