name: '👀 Auto assign'

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  call-workflow:
    uses: dshare-inc/.github/workflow-templates/auto-assign.yml@main
