name: ✅ Check Gradle (Test, Coverage, Lint)

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'feature/*'
    tags:
      - '*-*.*.*'
      - '*-*.*.*-*'
      - '*.*.*-*'
      - '*.*.*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - unlabeled
      - ready_for_review
  workflow_dispatch:

jobs:
  call-workflow:
    uses: dshare-inc/.github/.github/workflows/check-gradle.yml@main
