name: ✅ Check (Gradle)

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'feature/*'
    tags:
      - '*-*.*.*'
      - '*-*.*.*-*'
      - '*.*.*-*'
      - '*.*.*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - unlabeled
      - ready_for_review
  workflow_dispatch:

jobs:
  call-workflow:
    uses: dshare-inc/.github/.github/workflows/check-gradle.yml@main
    with:
      test_commands: 'test'
      build_exclude_commands: '-x test'
    secrets:
      AWS_ROLE_REGION: ${{ secrets.AWS_ROLE_REGION }}
      AWS_CODE_MANAGER_ROLE: ${{ secrets.AWS_CODE_MANAGER_ROLE }}
      AWS_ROLE_SESSION_DURATION: ${{ secrets.AWS_ROLE_SESSION_DURATION }}
      AWS_CODEARTIFACT_REGION: ${{ secrets.AWS_CODEARTIFACT_REGION }}
      AWS_CODEARTIFACT_DOMAIN: ${{ secrets.AWS_CODEARTIFACT_DOMAIN }}
      AWS_CODEARTIFACT_OWNER: ${{ secrets.AWS_CODEARTIFACT_OWNER }}
      CODECOV_REPO_TOKEN: ${{ secrets.CODECOV_REPO_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_REVIEW_NOTIFICATION_CHANNEL: ${{ secrets.SLACK_REVIEW_NOTIFICATION_CHANNEL }}
