name: '💔 Health check'

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  workflow:
    uses: dshare-inc/.github/.github/workflows/health-check.yml@main
    with:
      uri: ''
      max_attempts: 10
      retry_delay_second: '5s'
      channel: ''
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_HEALTH_CHECK_NOTIFICATION_CHANNEL: ${{ secrets.SLACK_HEALTH_CHECK_NOTIFICATION_CHANNEL }}
