name: 🚨 Hotfix Fast-track

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - labeled
      - unlabeled

jobs:
  workflow:
    uses: dshare-inc/.github/.github/workflows/hotfix-emergency-approve.yml@main

