name: 🚨 Hotfix

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  workflow:
    uses: dshare-inc/.github/.github/workflows/hotfix-emergency-approve.yml@main
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_HOTFIX_NOTIFICATION_CHANNEL: ${{ secrets.SLACK_HOTFIX_NOTIFICATION_CHANNEL }}
