name: '🎫 Jira Ticket Comment'

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  Check:
    name: Check JIRA Ticket
    runs-on: ubuntu-latest
    steps:
      - name: Extract Ticket
        id: jira
        run: |
          ORIGINAL=$(echo '${{ github.event.pull_request.title }}' | awk '/^([A-Z]+-[0-9]+)/{print $1}')

          echo "::set-output name=ticket::$ORIGINAL"

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: 'by dshare-bot, PR COMMENT (jira-ticket-comment)'
          direction: last

      - name: Create comment
        if: steps.fc.outputs.comment-id == '' && steps.jira.outputs.ticket != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🎫 Jira Issue
            > 이 PR은 Jira Issue가 존재합니다. 자세한 사항은 Jira에서 확인하시기 바랍니다.

            [https://dshare.atlassian.net/browse/${{ steps.jira.outputs.ticket }}](https://dshare.atlassian.net/browse/${{ steps.jira.outputs.ticket }})

            by dshare-bot, PR COMMENT (jira-ticket-comment)

      - name: Update comment
        if: steps.fc.outputs.comment-id != '' && steps.jira.outputs.ticket != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### 🎫 Jira Issue
            > 이 PR은 Jira Issue가 존재합니다. 자세한 사항은 Jira에서 확인하시기 바랍니다.

            [https://dshare.atlassian.net/browse/${{ steps.jira.outputs.ticket }}](https://dshare.atlassian.net/browse/${{ steps.jira.outputs.ticket }})

            by dshare-bot, PR COMMENT (jira-ticket-comment)

