name: '🎫 Jira Ticket Comment'

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  workflow:
    uses: dshare-inc/.github/.github/workflows/jira-ticket-comment.yml@main
