name: 'ðŸ· Empty Label'

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  Success:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        if: github.event.pull_request.labels.length > 0 || (github.event.label != null && github.event.label.name == 'hotfix ðŸš¨')
        run: |
          exit 0
      - name: Fail
        if: github.event.pull_request.labels.length < 1 && github.event.label.name != 'hotfix ðŸš¨'
        run: |
          exit 1
