name: '🏷 Empty Label'

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  Label:
    name: Check Label
    runs-on: ubuntu-latest
    steps:
      - name: Success
        if: github.event.pull_request.labels[0] != null
        run: |
          exit 0

      - name: Fail
        if: github.event.pull_request.labels[0] == null
        run: |
          exit 1
