name: 'ðŸ· Empty Label'

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  Success:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        on: github.event.pull_request.labels.length > 0
        run: |
          return 0
      - name: Fail
        on: github.event.pull_request.labels.length < 1
        run: |
          return 1
