name: '🏷 Empty Label'

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflow:
    uses: dshare-inc/.github/.github/workflows/pr-empty-label-check-comment.yml@main
