name: '⏫ Publish'

on:
  push:
    tags:
      - '*-*.*.*'
      - '*-*.*.*-*'
      - '*.*.*-*'
      - '*.*.*'

jobs:
  workflow:
    uses: dshare-inc/.github/.github/workflows/publish.yml@main
    with:
      type: '' # jdk / node
      jdk_version: '11.0'
      node_version: '14'
    secrets:
      AWS_ECR_REGION: ${{ secrets.AWS_ECR_REGION }}
      AWS_CODEARTIFACT_REGION: ${{ secrets.AWS_CODEARTIFACT_REGION }}
      AWS_CODEARTIFACT_DOMAIN: ${{ secrets.AWS_CODEARTIFACT_DOMAIN }}
      AWS_CODEARTIFACT_OWNER: ${{ secrets.AWS_CODEARTIFACT_OWNER }}
      AWS_ROLE_SESSION_DURATION: ${{ secrets.AWS_ROLE_SESSION_DURATION }}
      AWS_CODE_MANAGER_ROLE: ${{ secrets.AWS_CODE_MANAGER_ROLE }}
