name: 🔖 Versioning

on:
  workflow_dispatch:
    inputs:
      use_module:
        description: 'Use sub-module (path)'
        type: boolean
        required: false
        default: 'false'
      module:
        description: 'Choose the module for the prefix of version'
        required: false
        type: choice
        options:
          - 'Please select the module'
      suffix:
        description: 'Version suffix (e.g. rc, nightly)'
        required: false
      bump:
        description: 'Bump version type (using semver 2.0.0)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      bump_check:
        description: 'Recheck the bump type for validation'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  call-workflow:
    uses: dshare-inc/.github/.github/workflows/versioning.yml@main
    with:
      use_module: ${{ github.event.inputs.use_module }}
      module: ${{ github.event.inputs.module }}
      suffix: ${{ github.event.inputs.suffix }}
      bump: ${{ github.event.inputs.bump }}
      bump_check: ${{ github.event.inputs.bump_check }}
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_MAIL: ${{ secrets.GIT_USER_MAIL }}
